language: node_js
node_js: 5.3.0

sudo: required

services:
- docker

env:
  global:
  - DOCKER_USERNAME=goabouttech
  # DOCKER_PASSWORD
  - secure: Zrwq53qQ7XoNR7ofwh9KHPXlcBdQB+cJ5SVLpKWhaXmVp9WSF22iB9MrEyAXcq40GsycI6o2p0aU2oqD2Rqck3lBpGacjGuOmQjO9975950sD8ex1bxbp436Vsj2lLl3yeUH1vzIqDJ+kuaiEydmIH4afeKfGic01Fg6nRgddynM6Ck1q4KehI863DKuelYj+rOrFPh7u+AxhrhO0XyUHHqecYbQirAM/fBz4j23gA0rWEKQF1KwaDPnp+FPl3SBcJLc/U/aL86Dc2/+J9baStCGj8kJbZdq9ISQTomEoc3CLYldP5V/VaObO5tDI1NB5w7pRJ2DscNiErfJuvsB2xz7z2Z5+7LnVqY1NvI5fYDxaaPOfqRaFfBOCTk2OZuP1LFDwjj3Mbff0XWrNJ0Gq1OnI3KfrNWxyjpziNKUjfZAtCNUNF80CIgHaGYFVhMVpEbMvqvRqAQ3Zks2v/MMp+lEWF0sPk0CBWpK1D1sjmIexIERzHa+4otS7IhHPLxUYQNk0dE9tXLnQo7qjSs7ozkWwEKbE805vHekwNlWJ4bA0ZS3jgPU4qzzxt/0vEAJJGUU3CcFk1PxkfJ8wjdRWt74q/insfnLQtcw5YAz/sTv4/LEB/dOOjKHGaVwnVzppDrYwIfpcW1NUu+nkshjRJVllNorwoA+N4ohEWNHC3s=
  # TRAVIS_TOKEN
  - secure: Ln9n8W6yI/JeRiKE1RNJ43aG//aIIwmzkKPlvAm0QqzzE3R8w3tPK9atDLDfne0oYFLWEzuhLd9Lk3NAj9cX/iVc7XIieP3Q6Ci+HM4eTqC6DwaKqOzlamY9kFX2x3CFlOlse2oom+NQsYWHvqa86/5M5kjsLIN+2VzKgzoDpitirfWBMrDM0vtBL026tvEaxjobHLTEefPQQwiECq9GeuC/dwXHQ7PKvKeu3pU+bTdyRkQvK6lEX1WGBZ3DB1NHKwHWV9ZnBIdOxOhrLOMTZX4OjHnXDmayGQXE40169eSE38cMVWQBrWHEBUj/8YSThcO46VAOOeRR/5msrun+wXY2AT5GPEiuy1p+n4IOZ8XZZjiWWBlkDpgKfjsd46TdFosW0eWub65Yk7VyTcFc3QhzAiZboN0rwNPtVb39/sE4tnS6o9r5JaSrbupOcTCiCMVl6DoOTTIHxErkwrF4AzLx+0KdDf5aY+1BTJyCZ6Y0fREf3vGG0Q7U++nNRWzHifETO3XQT7QdXkXpTJ/vEZoa9uEjUDIKBX+Smd/0cN3qUVD2U1oyjl/fH0Q9oZIBgyYL2gmni3WCeJb5uf+AzWtRnmMf2ACtvzIyi4qDlQqZZDotJLAFekWcMrGqpnfoek6jltfE+pKyTEUT5nSChDrOaykxeKSgIveX4biGyZs=

install: true

before_script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script: ./build.sh

cache:
  apt: true
